### ISSUE TITLE
Can't connect to the NodeJS websocket using Chrome

### ISSUE THREAD

**Issue by jvorcak** [openshift/origin-server#1170]
Hi,

I've already described my problem here https://openshift.redhat.com/community/forums/openshift/websocket-support-possible-bug

In short ... I have create an application which is using Websockets on Openshift using NodeJS server.
My problem is that when I try to connect to my application's websocket using Firefox (from http://www.websocket.org/echo.html), it successfully connects to the NodeJS server and everything is working.

When I try the same thing using Chrome it just disconnect me and set the state of the websocket to 3.

In the Chrome developer console, when I try to connect to other websocket service (ws://echo.websocket.org), it at least shows 101 - Web socket Protocol Handshake

With NodeJS it just doesn't say anything. One week ago everything was working and I haven't changed my code.

**Comment by tiwillia** [comment]
This should have been resolved via https://bugzilla.redhat.com/show_bug.cgi?id=905647

@danmcp we can close this out.

@jvorcak if you are still experiencing this problem, please re-open this issue.
