### ISSUE TITLE
Current working directory should be where `setup.py` is

### ISSUE THREAD

**Issue by namn** [openshift/origin-server#1852]
Usually people write their `setup.py` according to the directory structure where `setup.py` resides in.

The openshift-origin-cartridge-python-2.6 cartridge breaks this convention by running `python setup.py develop` in the virtualenv directory.

**Comment by tiwillia** [comment]
We do not run `setup.py` in the virtualenv directory any longer. `setup.py` is run in `$OPENSHIFT_REPO_DIR`:

https://github.com/openshift/origin-server/blob/master/cartridges/openshift-origin-cartridge-python/usr/versions/shared/bin/control#L187

The virtualenv directory is $OPENSHIFT_PYTHON_DIR/virtenv:

https://github.com/openshift/origin-server/blob/master/cartridges/openshift-origin-cartridge-python/usr/versions/shared/lib/create-virtenv#L13

@dobbymoodge could you confirm the above? I am no python expert.

**Comment by dobbymoodge** [comment]
@tiwillia that seems true to me. FWIW, I don't think it matters which directory `setup.py` is called from; tools like `pkg_resources` (http://pythonhosted.org/setuptools/pkg_resources.html) are - generally, and almost certainly in this case - used to derive installation paths and python lib paths.

**Comment by tiwillia** [comment]
@dobbymoodge, thanks for the explanation!

@danmcp, we can close this one out.
