### ISSUE TITLE
Invalid configuration value in openshift-origin-dns-nsupdate.conf.example

### ISSUE THREAD

**Issue by brianredbeard** [openshift/origin-server#2684]
In the sample configuration file it is missing the sample line
```bash
#BIND_KEYVALUE=(HMAC-MD5|HMAC-SHA1|HMAC-SHA256|HMAC-512) # Default: HMAC-MD5
``` 
should actually have the option BIND_KEYALGORITHM as per line 25 in:

plugins/dns/nsupdate/config/initializers/openshift-origin-dns-nsupdate.rb

Relates to Issue #2678

**Comment by tiwillia** [comment]
This has been resolved in master with commit c598c233a484279b811107bd3862f83501b759ef

@danmcp we can close this one.
