### ISSUE TITLE
openshift-tc.service not starting on downloadable VM's

### ISSUE THREAD

**Issue by magnus919** [openshift/origin-server#3400]
"Node execution" errors are occurring with downloadable VM images. It would appear that openshift-tc.service isn't starting correctly on bootup, but can be started by hand.

**Comment by tiwillia** [comment]
This will be resolved alongside #6192

**Comment by tiwillia** [comment]
With the new vm image from issue #6192, the openshift-tc service starts on boot.

@danmcp we can close this.
