### ISSUE TITLE
IPv6 enabled on downloadable VM's

### ISSUE THREAD

**Issue by magnus919** [openshift/origin-server#3401]
Can IPv6 be enabled by default on downloadable VM images? It appears someone went to the trouble of shutting that off, which is normally enabled on Fedora. Was there something broken in IPv6 support that disabling IPv6 was fixing?

**Comment by tiwillia** [comment]
This is a [known limitation](https://bugzilla.redhat.com/show_bug.cgi?id=871569) of OpenShift m4 and earlier. There are components that require IPv4 and break IPv6 support. IPv6 is on the roadmap to be supported in [Origin v3](https://github.com/openshift/origin).

@danmcp we can close this out.
