### ISSUE TITLE
JBossEWS cartridge RPM install fail because of dependency on package tomcat7

### ISSUE THREAD

**Issue by ananich** [openshift/origin-server#3476]
Specfile contains reference to tomcat7*.rpm:
https://github.com/openshift/origin-server/blob/master/cartridges/openshift-origin-cartridge-jbossews/openshift-origin-cartridge-jbossews.spec

This RPM does not present in dependencies repository and there is no documentation which can tell where it is located.

**Comment by tiwillia** [comment]
There is a note about this in the [Administration Guide](https://docs.openshift.org/origin-m4/oo_administration_guide.html#list-available-cartridges) as well as detailed instructions on how to obtain the tomcat[6,7] rpms in the [M4 release notes](https://docs.openshift.org/origin-m4/oo_m4_release_notes.html#enabling-jboss-cartridges)

@danmcp we can close this out.
