### ISSUE TITLE
Connect-Timeout Issue on External Cartridges and Multiple DNS's

### ISSUE THREAD

**Issue by croteb** [openshift/origin-server#3546]
We are using a multiple DNS setup (an internal DNS for our own hosts) and an external DNS for all internet based hosts.

It appears that to clone a cartridge it uses a --connect-timeout of 2 seconds for the curl command.  We seem to have hit a situation where we were timing out before the external cartridge was downloaded and thus couldn't pull any external cartridges.  I believe this value should be user overridable, like the other parameters to the curl command?

https://github.com/openshift/origin-server/blob/master/controller/app/helpers/cartridge_cache.rb#L132

**Comment by tiwillia** [comment]
This issue was addressed by switching to using 'httpclient' and providing a configuration option (**CART_DOWNLOAD_CONN_TIMEOUT** in the broker.conf) for the connection timeout in https://github.com/openshift/origin-server/pull/3770.

@danmcp can we close this out?
