### ISSUE TITLE
nodejs cartridge requires either "main" in package.json; or a server.js file

### ISSUE THREAD

**Issue by grdryn** [openshift/origin-server#4074]
Hi,

I'm not very experienced with nodejs, so this issue may not actually be much of an issue. I also may be completely missing something obvious in the nodejs-0.10 cart.

I'm trying to make a project (pump.io -- not my own) easily deployable on openshift. The default way to start this is to run `npm start`. From my extremely limited experience with nodejs, this is quite a common way to start an application, and I was naively expecting the openshift cartridge to use that.
This application doesn't have a "main" key in the package.json file, neither does it have a server.js file (`npm start` points to bin/pump).

My first idea was to try to get a "main" key added to package.json, but that doesn't seem to be an optimal solution:
- It needs to be able to read a config file. Default locations are /etc/pump.io.json, and ~/.pump.io.json, neither of which are writeable by the user (on openshift online at least). Two possible solutions:
  - pass custom file path with '-c' parameter (makes "main" key openshift specific)
  - Set ${HOME} to ${OPENSHIFT_DATA_DIR} and put .pump.io.json in there. I can't seem to figure out how to do that (tried exporting in pre_start action hook with no luck) -- is there a way to do this?
- The "main" key seems to exist to be called when something else calls it as a dependency with e.g. require('pump.io') rather than running it as a standalone application (npm start). According to [nodejitsu](http://package.json.nodejitsu.com/), "main" is highly advised not to generate any side-effects such as starting a server or connecting to a database. I imagine, on the other hand, that apps running on openshift will usually have side effects such as these (such is this case with the pump.io example here). Is this an incorrect assumption?

Is there a way to specify a custom start action here (override the defaults of "main" falling back to server.js)? Or at least a way to set $HOME to a custom location? Or is there a better way to think about this?

I also found it difficult to actually find out what the start control action would attempt without reading the code. Again, this may be me reading in the wrong places or just being silly!

Would it make sense for the cartridge to attempt `npm start`?

Thanks for any insight or help that you can provide.

**Comment by tiwillia** [comment]
@grdryn, sorry for the very late response on this.

Since this issue was opened, the `use_npm` marker has been added to the nodejs cartridge. With this marker, an application can be started with 'npm start' rather than with a server.js file. A `main` directive shouldn't be required when using the `use_npm` marker.

As for the need to read a config file, the locations you specified will not be valid. You will need to make some modifications so that the configuration file is either read from within your git repository `$OPENSHIFT_REPO_DIR` or from within the data directory `$OPENSHIFT_DATA_DIR`. 

As for modifying the `$HOME` variable (not that you'll need to with the `use_npm` marker), this is currently not possible. The `$HOME` variable must be set to your gear's directory "/var/lib/openshift/<uuid>".

With that, you should be able to get `pump.io` working. Let us know if you run into any further problems.

**Comment by grdryn** [comment]
@tiwillia Thanks for replying. I managed to get something working back then (probably very horribly), & I happened to be playing with it only about 2 weeks ago and noticed the `use_npm` flag...it does just what I need! :+1: 

I've got a quickstart for it now here (although I still need to update it a bit): https://github.com/grdryn/pump.io/tree/openshift

**Comment by grdryn** [comment]
@tiwillia Also, I am changing the HOME to be $OPENSHIFT_DATA_DIR: https://github.com/grdryn/pump.io/blob/openshift/.openshift/action_hooks/pre_start_nodejs

Is that really bad? It seems to work fine.

**Comment by tiwillia** [comment]
@grdryn cartridges were designed around specific environment variables being set to the default and never changed. Here is a list of intentionally "read-only" environment variables: [System Environment Variables](https://docs.openshift.com/online/cartridge_specification_guide/environment_variables.html). Trying to overwrite any of these variables the proper way (`rhc env-set`) results in an error stating that the environment variable cannot be overwritten.

That said, there is only one issue I found where overwriting this variable could cause problems. When running gear `control` operations (start, stop, build, etc), we use the `$HOME` environment variable to check all cartridge manifests and find an haproxy cartridge. When changing `$HOME`, no web proxy cartridges will be found and some cartridge operations that depend on it may fail. This should only be a problem for scaled applications. If your application is not scaled, this won't be an issue.

Most operations that require to know the gear's home directory use the `$OPENSHIFT_HOMEDIR` variable, which remains the original `$HOME` directory even after exporting `$HOME` in `pre_start_*`.

**TL&DR;**
As long as your application isn't scaled, I don't immediately see how changing $HOME can cause any issues.
