### ISSUE TITLE
exceeded timeout of 230

### ISSUE THREAD

**Issue by lsde** [openshift/origin-server#4958]
origin rel3 is prone to this error already resolved in Online some time ago (https://bugzilla.redhat.com/show_bug.cgi?id=980955)

i'm trying to deploy a nodejs app (https://github.com/qq99/echoplexus) from web console resulting in following error and subsequent cartrige removal:
RESULT=SUCCESS STATUS=unprocessable_entity TIMESTAMP=1394774822 DATE=2014-03-13 TIME=22:27:02 ACTION=ADD_APPLICATION REQ_ID=8e55064a46de619dcea90db0a0ccfe3b USER_ID=531f1b6545f3e95917000003 LOGIN=lsde DOMAIN=1 The initial build for the application failed: Shell command '/sbin/runuser -s /bin/sh 5322920f45f3e9096d000001 -c "exec /usr/bin/runcon 'unconfined_u:system_r:openshift_t:s0:c0,c1005' /bin/sh -c \"gear postreceive --init >> /tmp/initial-build.log 2>&1\""' exceeded timeout of 230

**Comment by tiwillia** [comment]
This is a configurable timeout that can be modified on each node in the file `/opt/rh/ruby193/root/usr/libexec/mcollective/mcollective/agent/openshift.ddl`:
```
:timeout => 360 
```

The timeout is defined as 360, but the remainder is passed along as each step of the process completes. There were 230 seconds of the timeout left when the action timing out started, so a timeout of 230 was reported.

If you are deploying applications that will take longer than ~4 minutes to build, it is necessary to increase this timeout.

For more information, see the [Administration Guide](https://access.redhat.com/documentation/en-US/OpenShift_Enterprise/2/html/Administration_Guide/Component_Timeout_Value_Locations.html)

This specific issue/resolution is also documented in [Red Hat's knowledgebase](https://access.redhat.com/solutions/1238583)

@danmcp we can close this out.
