### ISSUE TITLE
Out of date documentation?

### ISSUE THREAD

**Issue by mhitza** [openshift/origin-server#5427]
Following the steps from http://openshift.github.io/documentation/oo_deployment_guide_vm.html and booting up the virtual machine I had issues with the user accounts that where supposed to be there.

openshift:openshift as the unix account on the VM, doesn't exists:

```bash
[root@broker-66587a openshift]# id openshift
id: openshift: no such user
```

And neither does admin:admin for the service account, which I've tried in to use to access openshift via the browser

**Comment by tiwillia** [comment]
Fixed in #5768 

@danmcp this can be closed.
