### ISSUE TITLE
OpenShift Origin on Amazon EC2 with Ansible

### ISSUE THREAD

**Issue by clasik** [openshift/origin-server#5511]
Hello. I am trying to install OpenShift Origin on Amazon EC2. I followed this guide: https://www.openshift.com/blogs/deploying-highly-available-openshift-origin-clusters-with-ansible
Step by step guide. I configured the file "group_vars / all": ec2_access_key: "XXXXXXXXXXXXXXX" ec2_secret_key: "XXXXxxxxxxXXXXXXXXXXXX" keypair: "my_key_pair" instance_type: "t1.micro" image: "ami-bf5021d6" group: "default" count: 1

And execute from my MAC: ansible-playbook -i ec2hosts ec2.yml -e id=openshiftv1 -e ansible_ssh_private_key_file=my_key_pair.pem --user root -vvvv

And ever i have somehting error like this:

fatal: [ec2-54-00-00-15.compute-1.amazonaws.com] => failed to transfer file to /root/.ansible/tmp/ansible-tmp-1402919043.76-125557901424971/yum: sftp> put /var/folders/rt/xnw2_wl9x935m0000gs/T/tmpfzGlBF /root/.ansible/tmp/ansible-tmp-1402919043.76-12588801424971/yum Uploading /var/folders/rt/xnw2_wl9x935m0000gs/T/tmpfzGlBF to /root/.ansible/tmp/ansible-tmp-1402919043.76-12588801424971/yum

Connected to ec2-54-00-00-15.compute-1.amazonaws.com. Connection closed

fatal: [ec2-54-00-00-237.compute-1.amazonaws.com] => SSH encountered an unknown error. The output was: OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011 debug1: Reading configuration data /etc/ssh_config debug1: /etc/ssh_config line 20: Applying options for * debug1: auto-mux: Trying existing master debug1: Control socket "/Users/user/.ansible/cp/ansible-ssh-ec2-54-00-00-237.compute-1.amazonaws.com-22-root" does not exist debug2: ssh_connect: needpriv 0 debug1: Connecting to ec2-54-00-00-237.compute-1.amazonaws.com [54.00.00.237] port 22. debug2: fd 3 setting O_NONBLOCK debug1: connect to address 54.00.00.237 port 22: Operation timed out ssh: connect to host ec2-54-00-00-237.compute-1.amazonaws.com port 22: Operation timed out

fatal: [ec2-54-00-00-216.compute-1.amazonaws.com] => {'msg': "One or more undefined variables: 'dict object' has no attribute u'ansible_eth0'", 'failed': True} fatal: [ec2-54-00-00-216.compute-1.amazonaws.com] => {'msg': "One or more undefined variables: 'dict object' has no attribute u'ansible_eth0'", 'failed': True} fatal: [ec2-54-00-00-212.compute-1.amazonaws.com] => {'msg': "One or more undefined variables: 'dict object' has no attribute u'ansible_eth0'", 'failed': True} fatal: [ec2-54-00-00-212.compute-1.amazonaws.com] => {'msg': "One or more undefined variables: 'dict object' has no attribute u'ansible_eth0'", 'failed': True} fatal: [ec2-54-00-00-232.compute-1.amazonaws.com] => {'msg': "One or more undefined variables: 'dict object' has no attribute u'ansible_eth0'", 'failed': True} fatal: [ec2-54-00-00-232.compute-1.amazonaws.com] => {'msg': "One or more undefined variables: 'dict object' has no attribute u'ansible_eth0'", 'failed': True}

**Comment by tiwillia** [comment]
@clasik @detiber Is there any reason to keep this issue open, or can we go ahead and close it?

**Comment by clasik** [comment]
Close it, thanks.
