### ISSUE TITLE
oo-install fails to start required services

### ISSUE THREAD

**Issue by untsakas** [openshift/origin-server#5693]
Running ``oo-diagnostics -v`` after installing OpenShift Origin using oo-install (all-in-one installation) identifies that required services ``openshift-watchman``, ``cgred`` and ``cgconfig`` are not running on the server.

**Comment by tiwillia** [comment]
After the change, `cgred` and `cgconfig` are started successfully, but `openshift-watchman` is not started:
```
WARN: test_services_enabled
      The following service(s) are not currently started:
        openshift-watchman
      Unless you know they are not needed, please start these services.
```

oo-install does set the service to start on the next boot:
```
# chkconfig | grep watchman
openshift-watchman	0:off	1:off	2:on	3:on	4:on	5:on	6:off
```

**Comment by tiwillia** [comment]
This is resolved with https://github.com/openshift/puppet-openshift_origin/pull/402 and should be pushed to puppet forge shortly.

@danmcp we can close this one out.
