### ISSUE TITLE
unable to install MariaDB cartridge on CentOS v6.5 (spec file needs to be updated)

### ISSUE THREAD

**Issue by aerotodor** [openshift/origin-server#5759]
If you run OO m4 on Centos v6.5 and try to install MariaDB cartridge, it will fail (missing dependencies, mariadb-server, mariadb-devel)

the problem should be fixed in openshift-origin-cartridge-mariadb.spec (mariadb-server is always required, should be required only on Fedora & RHEL7)

```
Requires:      mariadb-server
Requires:      mariadb-devel

# For RHEL6 install mysql55 from SCL
%if 0%{?rhel}
Requires:      mariadb55
Requires:      mariadb55-mariadb-devel
%endif
````

**Comment by tiwillia** [comment]
I can verify this issue. Thanks for submitting. We'll need to fix this.
