### ISSUE TITLE
Expose `haproxy-sni-proxy` mapped ports as environmental variables

### ISSUE THREAD

**Issue by grgrzybek** [openshift/origin-server#5820]
We have such mappings in https://github.com/jboss-fuse/fuse-openshift-cartridge:
```
...
  - Private-IP-Name:   IP
    Private-Port-Name: APP_PORT_1
    Private-Port:      3001
    Public-Port-Name:  APP_PORT_1_PROXY_PORT
    Options:           { "ssl_to_gear": true }
...
  - Private-IP-Name:   IP
    Private-Port-Name: APP_TLS_PORT_1
    Private-Port:      4001
    Public-Port-Name:  APP_TLS_PORT_1_PROXY_PORT
    Protocols: [tls]
    Mappings:
    - Frontend: 'TLS_PORT_6'
      Backend: ''
...
```
I see [here][1], that edpoinrs with `ssl_to_gear` option set have `Public-Port-Name` exposed as env variable to created application. Is there a chance to do the same for other endpoints? In case of APP_TLS_PORT_1_PROXY_PORT the mappings[0].frontend could be mapped to actual port from `HaproxySNIProxyDB.get_ports`. For endpoints without `ssl_to_gear` we could do only:
```
@container.add_env_var(endpoint.public_port_name, mapped port from SNI proxy database)
```

[1]: https://github.com/openshift/origin-server/blob/master/node/lib/openshift-origin-node/model/v2_cart_model.rb#L924

**Comment by tiwillia** [comment]
Fixed with d204bd72af4f15e6a51c2303329847b2ce4e679e and tracked in [BZ#1144788](https://bugzilla.redhat.com/show_bug.cgi?id=1144788)

@danmcp we can close this out
