### ISSUE TITLE
Can't connect to OpenShift after OpenShift has disabled SSLv3

### ISSUE THREAD

**Issue by Gebsun** [openshift/origin-server#5895]
We cannot establish connection from external host to OpenShift via SSL, after SSLv3 has been deisable.
From JAVA (1.6.0_26 ) we get error:
Caused by: java.lang.RuntimeException: Could not generate DH keypair
Caused by: java.security.InvalidAlgorithmParameterException: Prime size must be multiple of 64, and can only range from 512 to 1024 (inclusive)

**Comment by tiwillia** [comment]
Most OpenJDK 1.7 and I believe all OpenJDK 1.6 versions only support EDH key sizes up to 1024 bits. Recent security updates to httpd among other software allow EDH key sizes larger than 1024 bits. Your java client is old and cannot handle the new, larger key sizes.

You should be able to resolve this issue by updating to either OpenJDK 1.8 (Java 8) or a version of OpenJDK 1.7 with the EDH size limitation increased. See [Bug JDK-6521495](https://bugs.openjdk.java.net/browse/JDK-6521495) for more info.

@danmcp we can likely close this one out.
