### ISSUE TITLE
Jenkins Debug Marker does not work 

### ISSUE THREAD

**Issue by sferich888** [openshift/origin-server#6062]
https://github.com/openshift/origin-server/blob/master/cartridges/openshift-origin-cartridge-jenkins/bin/control#L64-L66

Setting the marker above does not produce FINE or FINER logging in the jenkins logs.

**Comment by sferich888** [comment]
Note I have also tried the following: 

$ --> rhc env set JENKINS_OPTS="-verbose:gc -Xloggc:/var/lib/openshift/UUID/app-root/logs/gc.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Djava.util.logging.loglevel=FINER" --app APPNAME

$ --> rhc env set JENKINS_WAR_PATH="/usr/lib/jenkins/jenkins.war --debug=9" --app APPNAME

Both also fail to increase the log level.

**Comment by tiwillia** [comment]
I may be wrong here, as I am no java expert, but it appears to be working fine. The "enable_debugging" marker for jenkins adds the following to the java startup options:
```
-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=${OPENSHIFT_JENKINS_IP}:7600,suspend=n
```

I believe this just enables the remote debugger. Testing this on the most recent codebase, I can see it is working as expected:
```
> ps aux | grep java
5568     11483  2.8  7.3 1161100 140676 ?      Sl   15:45   0:11 /etc/alternatives/jre/bin/java -Xms20m -Xmx168m -XX:MaxPermSize=100m -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Djava.awt.headless=true -Dhudson.udp=-1 -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=127.10.224.1:7600,suspend=n
[...] cut for clarity

> lsof | grep LISTEN
java    11483     5568    4u  IPv4 19816704      0t0  TCP 127.10.224.1:7600 (LISTEN)
```

As for being unable to increase the log level with command line options, this is stated in the [Jenkins wiki](https://wiki.jenkins-ci.org/display/JENKINS/Logging):
>Unfortunately, there is no simple way in Jenkins to send log messages generated by Jenkins himself or by any plugins to the console, to a file or anywhere else. No matter what command line options you will use, you just won't succeed. It won't even help if you inject a java.util.logging configuration file directly into the JVM as Jenkins will override any settings in there programmatically.

So, I think that behavior is to-be-expected.

**Comment by danmcp** [comment]
@tiwillia Your analysis looks correct to me.
