### ISSUE TITLE
openshift node start fails

### ISSUE THREAD

**Issue by jwhonce** [openshift/origin-server#6110]
When using /usr/bin/openshift start node --loglevel=5 --master=https://10.240.18.240:8443...

/usr/bin/openshift start node fails with "unknown flag: --master", using any option other than --loglevel fails. This prevents the node from starting.

This is a build as of 020dd17

@deads2k Clayton asked for you to look at this.

**Comment by detiber** [comment]
@jwhonce This is fixed with the changes ansible changes I have pending.

**Comment by deads2k** [comment]
Also, because of a bug in cobra (see https://github.com/openshift/origin/pull/1257) the message is wrong, so I'll need the entire execution line.  That indicates that you've at least one misspelled argument, but it's not necessarily master.

**Comment by jwhonce** [comment]
@deads2k 

+ /usr/bin/openshift start node --loglevel=5 --master=https://10.240.18.240:8443 --hostname=10.240.117.103 --kubeconfig=/var/lib/openshift/openshift.local.certificates/admin/.kubeconfig '--images=openshift/origin-${component}:${version}'

**Comment by deads2k** [comment]
`--master` is gone.  You reference the master by specifying the correct value inside your --kubeconfig file.

**Comment by tiwillia** [comment]
I believe this was actually intended for https://github.com/openshift/origin

@jwhonce can we close this out?
