### ISSUE TITLE
Buy ssl certificates for www.openshift.org

### ISSUE THREAD

**Issue by tvvocold** [openshift/origin-server#6194]
When users came in https://www.openshift.com then hit the "Join the community" button, they will got a "NET::ERR_CERT_COMMON_NAME_INVALID " error in opening https://www.openshift.org

**Comment by tvvocold** [comment]
@rhamilto

**Comment by sztsian** [comment]
@tvvocold @nhr Now I get a ssl certificate signed by "DigiCert Inc" so I assume now this should be closed as FIXED.

**Comment by tvvocold** [comment]
Cool
