### ISSUE TITLE
Failed to run Kubelet during installation of openshift origin server on ubunto

### ISSUE THREAD

**Issue by kamranIoTDeveloper** [openshift/origin-server#6450]
Error Description:
failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "systemd" is different from docker cgroup driver: "cgroupfs"

**Comment by rhatdan** [comment]
This usually means you are running a cri-o that is configured to  use systemd and a test that expects it to be using cgroupfs.  You can change the /etc/crio/crio.conf file to use cgroupfs or you can change your test suite to use systemd.

**Comment by kamranIoTDeveloper** [comment]
@rhatdan thanks problem solved by matching cgroup driver of kubelet and docker (Changing cgroup driver in docker.service to systemd)
