### ISSUE TITLE
Clarification on the license of pam_openshift

### ISSUE THREAD

**Issue by mscherer** [openshift/origin-server#715]
According to the pam_openshift.c source code, the module is under the same liense as openshift, but also under GPL. However, the GPL version is not explicited, and the spec file say "GPL" without a version, which would be problematic for inclusion in Fedora later ( as I assume this will end in Fedora, i decided to be proactive ) . The license shipped is a GPL v2 copy. Could the situation be clarified ( ie, just saying the version in the spec file, and adding this is under a double license would be enough IMHO )

**Comment by tiwillia** [comment]
The spec file has been modified to include the GPL version (v2):

  https://github.com/openshift/origin-server/blob/master/pam_openshift/pam_openshift.spec#L6

However, according to Fedora's [Dual-Licensing Guidelines](https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#Dual_Licensing_Scenarios) both licenses should be specified in the spec file.

The text in the `pam_openshift.c` file looks like a BSD license, but does not match the official BSD license texts: https://fedoraproject.org/wiki/Licensing:BSD?rd=Licensing/BSD

@danmcp can you comment on this at all? Are any further changes necessary?

**Comment by danmcp** [comment]
There isn't any further push to get into v2 Fedora so I am closing.
